const MAIN_WINDOW_WIDTH = 1080;
const MAIN_WINDOW_HEIGHT = 660;
const MODAL_WINDOW_HEIGHT = 570;
const MODAL_WINDOW_WIDTH = 720;

module.exports = {
  MAIN_WINDOW_WIDTH,
  MAIN_WINDOW_HEIGHT,
  MODAL_WINDOW_WIDTH,
  MODAL_WINDOW_HEIGHT,
};
